# credit to source: https://towardsdatascience.com/how-to-run-postgresql-using-docker-15bf87b452d4
version: '3.3'
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - /home/sean/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
